import sequelize from "../config/db.js";
import { DataTypes } from "sequelize";

const Vote = sequelize.define(
	"Vote",
	{
		// uuid generated by firebase's anonymous auth
		anonId: {
			type: DataTypes.UUID,
			allowNull: false,
		},
		// the value of the vote, 'DA' or 'NU'
		voteOption: {
			type: DataTypes.ENUM("DA", "NU"),
			allowNull: false,
		},
		// the id of the play the user voted for ; also foreign key
		votedPlayId: {
			type: DataTypes.INTEGER,
			allowNull: false,
			primaryKey: true,
			references: {
				model: "Plays",
				key: "playId",
			},
		},
	},
	{
		tableName: "Votes",
		freezeTableName: true,
	}
);

export default Vote;
